spring:
    application:
        name: ms_config
    cloud:
        config:
            server:
                git:
                    uri: https://github.com/muspriandi/ms_config
                    search-paths: server-config/