spring:
    application:
        name: ms_config
    cloud:
        config:
            server:
                git:
                    uri: https://github.com/muspriandi/config-server
                    search-paths: server-config/
server:
  port: 8888