spring:
    application:
        name: ms_config
    cloud:
        config:
            server:
                git:
                    # uri: https://github.com/muspriandi/config-server
                    uri: D:\Cinema21\Devs\Common\spring-cloud-config
                    search-paths: server-config/
server:
  port: 8888

jasypt.encryptor.password: test123