spring:
    security:
        basic:
            enabled: true
        user:
            name: root
            password: root
    application:
        name: ms_config
    cloud:
        config:
            server:
                git:
                    # uri: https://github.com/muspriandi/config-server
                    uri: D:\Cinema21\Devs\Common\spring-cloud-config
                    search-paths: server-config/
                    default-label: main
server:
  port: 8888

# jasypt.encryptor.password: test123