server.port: 8080

management.endpoints.web.exposure.include: "refresh"

spring:
    application:
        name: ms-client
    config:
        import: optional:configserver:http://localhost:8888
    cloud:
        config:
            uri: http://localhost:8888
            username: root
            password: root
