hi: Default

server.port: 8080

management.endpoints.web.exposure.include: "refresh"

spring:
    application:
        name: ms_client
    config:
        import: optional:configserver:http://localhost:8888